services:
  frontend:
    image: todo-app-frontend-dev
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    # ports:
    #   - 5173:5173
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api
    volumes:
      - ./todo-frontend:/usr/src/app
    container_name: todo-app-frontend

  backend:
    image: todo-app-backend-dev
    build:
      context: ./todo-backend
      dockerfile: dev.Dockerfile
    # ports:
    #   - 3000:3000
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./todo-backend:/usr/src/app
    container_name: todo-app-backend
    depends_on: [ mongo, redis ]

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: todo-app-reverse-proxy
    depends_on: [ frontend, backend ]

  mongo:
    image: mongo
    # ports:
    #   - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    container_name: todo-app-mongo

  redis:
    image: redis
    # ports:
    #   - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis_data:/data
    container_name: todo-app-redis

volumes:
  mongo_data:
  redis_data: