services:
  frontend:
    image: todo-app-frontend
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    container_name: todo-app-frontend

  backend:
    image: todo-app-backend
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://redis:6379
    container_name: todo-app-backend
    depends_on: [ mongo, redis ]

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: todo-app-reverse-proxy
    depends_on: [ frontend, backend ]

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
    container_name: todo-app-mongo

  redis:
    image: redis
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis_data:/data
    container_name: todo-app-redis

volumes:
  mongo_data:
  redis_data: