services:
  backend:
    image: phonebook-app-backend
    container_name: phonebook-app-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://phonebook_backend_user:secure_password_123@mongo:27017/phonebook
    depends_on:
      - mongo

  frontend:
    image: phonebook-app-frontend
    container_name: phonebook-app-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend

  mongo:
    image: mongo
    container_name: phonebook-app-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=phonebook
    volumes:
      - ./backend/models/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db

  nginx:
    image: nginx:1.29.4-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: phonebook-app-reverse-proxy
    depends_on: [ frontend, backend ]

volumes:
  mongo-data: